apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prunetestapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdappdemo  
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Nginx_Deployment_Prune
    repoURL: 'https://github.com/yashjain10038/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
