apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standalone-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Nginx_Deployment
    repoURL: 'https://github.com/yashjain10038/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
